"use client";

import { useEffect, useRef, useState } from "react";

type Task = { id:string; time:string; title:string; category:string; done:boolean; xp:number };
type Habit = { id:string; name:string; streak:number; done:boolean };
type Skill = { id:string; phase:number; name:string; status:0|1|2 };
type Tx = { id:string; label:string; amount:number; type:"income"|"expense" };
type AppData = { xp:number; streak:number; note:string; tasks:Task[]; habits:Habit[]; skills:Skill[]; transactions:Tx[]; journal:Record<string,string> };
type View = "Inicio"|"Mi día"|"Hábitos"|"Roadmap"|"Finanzas"|"Diario"|"Imprevistos"|"Ajustes";

// ── DATOS INICIALES: nacen de los documentos personales de Moisés. ──────────
const phases = [
  ["HTML","CSS","JavaScript","Git","GitHub","Linux","SQL"],
  ["React","Node.js","Express","APIs REST","Postman"],
  ["TypeScript","PostgreSQL","Docker","Testing"],
  ["AWS","CI/CD","Kubernetes","IA aplicada"],
  ["Redes","Python","OWASP Top 10","Nmap","Wireshark","Burp Suite","DevSecOps","Seguridad cloud"],
];
const initial: AppData = {
  xp:1240, streak:12, note:"",
  tasks:[
    ["04:30","Despertar, agua y tender la cama","Personal",true,5],
    ["05:05","Desayuno y preparar comida","Alimentación",true,5],
    ["06:00","Formación en Campuslands","Estudio",false,20],
    ["13:40","Almuerzo y recuperación","Descanso",false,5],
    ["14:10","Entrenamiento físico (1.5 h)","Entrenamiento",false,15],
    ["16:00","Estudio profundo de JavaScript","Estudio",false,20],
    ["19:00","Inglés y proyecto personal","Inglés",false,15],
    ["20:30","Planear mañana y revisión nocturna","Planeación",false,10],
  ].map((x,i)=>({id:`t${i}`,time:x[0] as string,title:x[1] as string,category:x[2] as string,done:x[3] as boolean,xp:x[4] as number})),
  habits:["Estudiar tecnología","Inglés mínimo una hora","Entrenar 1.5 horas","Actualizar GitHub","Controlar gastos","Revisión nocturna"].map((name,i)=>({id:`h${i}`,name,streak:[12,8,4,3,6,9][i],done:i===0||i===3})),
  skills:phases.flatMap((items,p)=>items.map((name,i)=>({id:`s${p}-${i}`,phase:p+1,name,status:(p===0&&i<2?2:p===0&&i===2?1:0) as 0|1|2}))),
  transactions:[{id:"m1",label:"Ingreso mensual",amount:1900000,type:"income"},{id:"m2",label:"Arriendo",amount:650000,type:"expense"},{id:"m3",label:"Alimentación",amount:280000,type:"expense"},{id:"m4",label:"Transporte y gasolina",amount:150000,type:"expense"}],
  journal:{priority:"",planB:"",step:"",win:"",lesson:"",thanks:""}
};
const menu:View[]=["Inicio","Mi día","Hábitos","Roadmap","Finanzas","Diario","Imprevistos","Ajustes"];
const symbols=["⌂","✓","↻","⌁","$","✎","!","⚙"];
const money=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});

// ── COMPONENTE PRINCIPAL: controla navegación, acciones y persistencia. ──────
export default function Home(){
 const [view,setView]=useState<View>("Inicio"),[data,setData]=useState<AppData>(initial),[ready,setReady]=useState(false),[light,setLight]=useState(true),[toast,setToast]=useState("");
 const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{if("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(()=>undefined);const request=indexedDB.open("norte-personal",1);request.onupgradeneeded=()=>request.result.createObjectStore("state");request.onsuccess=()=>{const get=request.result.transaction("state").objectStore("state").get("profile");get.onsuccess=()=>{if(get.result)setData(get.result);setReady(true)}};request.onerror=()=>setReady(true)},[]);
 useEffect(()=>{if(!ready)return;const request=indexedDB.open("norte-personal",1);request.onsuccess=()=>request.result.transaction("state","readwrite").objectStore("state").put(data,"profile")},[data,ready]);
 const done=data.tasks.filter(t=>t.done).length, habitDone=data.habits.filter(h=>h.done).length, skillDone=data.skills.filter(s=>s.status===2).length;
 const income=data.transactions.filter(t=>t.type==="income").reduce((a,b)=>a+b.amount,0),expense=data.transactions.filter(t=>t.type==="expense").reduce((a,b)=>a+b.amount,0);
 const level=Math.min(10,Math.floor(data.xp/500)+1), levelNames=["Principiante","Aprendiz","Explorador","Practicante","Desarrollador Junior","Desarrollador Competente","Profesional","Especialista","Mentor","Maestro"];
 const ping=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2200)};
 const toggleTask=(id:string)=>{const target=data.tasks.find(t=>t.id===id)!;setData({...data,xp:Math.max(0,data.xp+(target.done?-target.xp:target.xp)),tasks:data.tasks.map(t=>t.id===id?{...t,done:!t.done}:t)})};
 const addTask=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),title=String(f.get("title")||"").trim();if(!title)return;setData({...data,tasks:[...data.tasks,{id:crypto.randomUUID(),time:String(f.get("time")),title,category:String(f.get("category")),done:false,xp:10}].sort((a,b)=>a.time.localeCompare(b.time))});e.currentTarget.reset();ping("Actividad agregada")};
 const backup=()=>{const a=document.createElement("a"),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.href=url;a.download=`norte-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);ping("Copia creada")};
 const restore=async(e:React.ChangeEvent<HTMLInputElement>)=>{try{const f=e.target.files?.[0];if(f){setData(JSON.parse(await f.text()));ping("Copia restaurada")}}catch{ping("Archivo no válido")}};
 if(!ready)return <main className="loading">Preparando tu espacio personal…</main>;
 return <div className={`app ${light?"light":""}`}>
  {/* NAVEGACIÓN LATERAL: visible en computador. */}
  <aside className="sidebar"><div className="brand"><span>N</span><div><b>NORTE</b><small>Sistema personal</small></div></div><nav>{menu.map((m,i)=><button key={m} onClick={()=>setView(m)} className={view===m?"active":""}><i>{symbols[i]}</i>{m}</button>)}</nav><div className="goal"><small>OBJETIVO PRINCIPAL</small><p>Conseguir un excelente empleo en desarrollo y evolucionar hacia ciberseguridad.</p><Progress value={skillDone/data.skills.length*100}/><b>{skillDone} de {data.skills.length} competencias</b></div><button className="theme" onClick={()=>setLight(!light)}>{light?"☾ Modo oscuro":"☀ Modo claro"}</button></aside>
  {/* CONTENIDO DEL MÓDULO SELECCIONADO. */}
  <main className="content"><header><div><em>CONSTRUYENDO UNA CARRERA INTERNACIONAL</em><h1>{view==="Inicio"?"Buen día, Moisés.":view}</h1><p>{new Date().toLocaleDateString("es-CO",{weekday:"long",day:"numeric",month:"long"})} · Bucaramanga</p></div><div className="saved"><i>●</i> Guardado local <b>MO</b></div></header>
   {view==="Inicio"&&<><section className="focus"><div><em>ENFOQUE DE HOY</em><h2>Los fundamentos primero. La constancia hace el resto.</h2><p>Avanza con intención, sin sacrificar descanso ni entrenamiento.</p></div><strong>{Math.round(done/data.tasks.length*100)}%<small>día completado</small></strong></section><section className="stats"><Stat label="NIVEL PROFESIONAL" value={`${level}. ${levelNames[level-1]}`} note={`${data.xp} XP acumulados`} progress={(data.xp%500)/5}/><Stat label="RACHA ACTUAL" value={`${data.streak} días`} note="Tu mejor racha: 18 días"/><Stat label="HÁBITOS DE HOY" value={`${habitDone} / ${data.habits.length}`} note="Consistencia sobre perfección" progress={habitDone/data.habits.length*100}/><Stat label="SALDO DEL MES" value={money.format(income-expense)} note={`${money.format(expense)} en gastos`}/></section><section className="dash"><div className="panel"><Title title="Tu ruta de hoy" sub={`${done} de ${data.tasks.length} actividades`} action={()=>setView("Mi día")}/><div className="timeline">{data.tasks.slice(0,7).map(t=><TaskRow key={t.id} task={t}/>)}</div></div><div className="stack"><div className="panel next"><em>PRÓXIMO BLOQUE</em><b>{data.tasks.find(t=>!t.done)?.time||"Listo"}</b><h3>{data.tasks.find(t=>!t.done)?.title||"Día completado"}</h3><p>Tu siguiente acción concreta</p></div><div className="panel"><Title title="Chequeo personal" sub="¿Cómo está tu energía?"/><div className="energy"><button>😮‍💨<small>Baja</small></button><button className="selected">🙂<small>Estable</small></button><button>⚡<small>Alta</small></button></div><textarea value={data.note} onChange={e=>setData({...data,note:e.target.value})} placeholder="¿Qué necesitas recordar hoy?"/></div><div className="panel route"><Title title="Ruta de 24 meses" sub="De fundamentos a seguridad" action={()=>setView("Roadmap")}/><Progress value={skillDone/data.skills.length*100}/><div><span>Fundamentos</span><span>Empleo junior</span><span>Ciberseguridad</span></div></div></div></section></>}
   {view==="Mi día"&&<section className="two"><div className="panel"><Title title="Rutina de hoy" sub="Adáptala a clases, trabajo, cansancio o imprevistos"/><div className="timeline">{data.tasks.map(t=><TaskRow key={t.id} task={t}/>)}</div></div><aside className="panel sticky"><h3>Nueva actividad</h3><form onSubmit={addTask}><label>Actividad<input name="title" placeholder="Ej. Practicar JavaScript" required/></label><div className="formrow"><label>Hora<input name="time" type="time" defaultValue="18:00"/></label><label>Categoría<select name="category"><option>Estudio</option><option>Inglés</option><option>Entrenamiento</option><option>Proyecto</option><option>Personal</option><option>Imprevisto</option></select></label></div><button className="primary">Agregar al día</button></form><blockquote><b>Regla del mentor</b><p>Ajustar el día no significa abandonar el objetivo.</p></blockquote></aside></section>}
   {view==="Hábitos"&&<><section className="sectionhead"><div><em>CONSISTENCIA SOBRE PERFECCIÓN</em><h2>{habitDone} hábitos completados hoy</h2></div><strong>{Math.round(habitDone/data.habits.length*100)}%</strong></section><section className="habits">{data.habits.map(h=><button key={h.id} className={h.done?"done":""} onClick={()=>setData({...data,habits:data.habits.map(x=>x.id===h.id?{...x,done:!x.done,streak:x.done?x.streak-1:x.streak+1}:x)})}><i>{h.done?"✓":""}</i><span><b>{h.name}</b><small>Meta personal · +15 XP</small></span><strong>{h.streak}🔥</strong></button>)}</section></>}
   {view==="Roadmap"&&<><section className="sectionhead"><div><em>PLAN 2026–2030</em><h2>De fundamentos a ciberseguridad</h2><p>Demanda comprobada, proyectos reales y revisión trimestral.</p></div><strong>{Math.round(skillDone/data.skills.length*100)}%<small>dominio global</small></strong></section><div className="phases">{phases.map((_,p)=><section className="panel phase" key={p}><i>{p+1}</i><div><h3>{["Fundamentos","Desarrollo profesional","Backend moderno","Tecnologías avanzadas","Ciberseguridad"][p]}</h3><p>Fase {p+1} de 5</p><div className="skills">{data.skills.filter(s=>s.phase===p+1).map(s=><button key={s.id} className={`s${s.status}`} onClick={()=>setData({...data,skills:data.skills.map(x=>x.id===s.id?{...x,status:((x.status+1)%3) as 0|1|2}:x)})}><i>{s.status===2?"✓":s.status===1?"◐":"○"}</i>{s.name}<small>{["Pendiente","En progreso","Dominado"][s.status]}</small></button>)}</div></div></section>)}</div></>}
   {view==="Finanzas"&&<section className="two"><div><section className="stats finance"><Stat label="INGRESOS" value={money.format(income)} note="Este mes"/><Stat label="GASTOS" value={money.format(expense)} note={`${Math.round(expense/income*100)}% de ingresos`}/><Stat label="DISPONIBLE" value={money.format(income-expense)} note="Saldo proyectado"/></section><div className="panel"><Title title="Movimientos" sub="Información privada en este dispositivo"/><div className="tx">{data.transactions.map(t=><div key={t.id}><i className={t.type}>{t.type==="income"?"+":"−"}</i><b>{t.label}</b><strong>{t.type==="income"?"+":"−"}{money.format(t.amount)}</strong></div>)}</div></div></div><aside className="panel sticky"><h3>Registrar movimiento</h3><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),amount=Number(f.get("amount")),label=String(f.get("label"));if(amount&&label){setData({...data,transactions:[...data.transactions,{id:crypto.randomUUID(),label,amount,type:String(f.get("type")) as "income"|"expense"}]});e.currentTarget.reset();ping("Movimiento guardado")}}}><label>Concepto<input name="label" placeholder="Ej. Alimentación" required/></label><label>Valor<input name="amount" type="number" min="1" required/></label><label>Tipo<select name="type"><option value="expense">Gasto</option><option value="income">Ingreso</option></select></label><button className="primary">Guardar movimiento</button></form></aside></section>}
   {view==="Diario"&&<section className="journal"><JournalBlock title="REVISIÓN DE LA MAÑANA" fields={[["priority","¿Cuál es mi prioridad principal?"],["planB","¿Qué riesgo puede afectarme y cuál es mi plan B?"],["step","¿Qué haré por mi objetivo profesional?"]]}/><JournalBlock title="REVISIÓN DE LA NOCHE" fields={[["win","¿Qué salió bien y cuál fue mi avance?"],["lesson","¿Qué aprendí y qué error no repetiré?"],["thanks","¿Qué agradezco hoy?"]]}/></section>}
   {view==="Imprevistos"&&<><section className="sectionhead"><div><em>PLAN B, NO CULPA</em><h2>Gestiona lo que no controlas</h2></div></section><section className="risks">{[["Congestión o cierre de puente","MEDIO","Salir 20 minutos antes y conservar una ruta alternativa."],["Cansancio acumulado","ALTO","Reducir el bloque nocturno y priorizar sueño suficiente."],["Fallo de internet","BAJO","Mantener recursos descargados para estudiar sin conexión."]].map(r=><article className="panel" key={r[0]}><i className={r[1].toLowerCase()}>{r[1]}</i><h3>{r[0]}</h3><p>{r[2]}</p></article>)}</section></>}
   {view==="Ajustes"&&<section className="settings"><div className="panel"><em>DATOS Y PRIVACIDAD</em><h2>Tu información te pertenece</h2><p>NORTE guarda tus hábitos, notas y finanzas en IndexedDB, dentro de este dispositivo. No los envía a servidores.</p><div className="actions"><button onClick={backup}><i>↓</i><span><b>Exportar copia JSON</b><small>Descarga todos tus datos</small></span></button><button onClick={()=>fileRef.current?.click()}><i>↑</i><span><b>Restaurar copia</b><small>Importa una copia anterior</small></span></button><input hidden ref={fileRef} type="file" accept="application/json" onChange={restore}/></div></div><div className="panel profile"><h3>Perfil personal</h3><dl><div><dt>Nombre</dt><dd>Moisés</dd></div><div><dt>Formación</dt><dd>Campuslands</dd></div><div><dt>Meta</dt><dd>Desarrollo → Ciberseguridad</dd></div><div><dt>Horizonte</dt><dd>2026–2030</dd></div></dl><button onClick={()=>confirm("¿Restablecer los datos iniciales?")&&setData(initial)}>Restablecer datos</button></div></section>}
  </main>
  {/* NAVEGACIÓN INFERIOR: acceso táctil en teléfono. */}<nav className="mobile">{menu.slice(0,5).map((m,i)=><button key={m} className={view===m?"active":""} onClick={()=>setView(m)}><i>{symbols[i]}</i><small>{m}</small></button>)}</nav>{toast&&<div className="toast">{toast}</div>}
 </div>;
 function TaskRow({task}:{task:Task}){return <div className={`task ${task.done?"done":""}`}><button onClick={()=>toggleTask(task.id)}>{task.done?"✓":""}</button><time>{task.time}</time><span><b>{task.title}</b><small>{task.category} · +{task.xp} XP</small></span><i/></div>}
 function JournalBlock({title,fields}:{title:string;fields:string[][]}){return <div className="panel"><em>{title}</em><h2>Escribe con honestidad</h2>{fields.map(([key,label])=><label className="question" key={key}><b>{label}</b><textarea value={data.journal[key]} onChange={e=>setData({...data,journal:{...data.journal,[key]:e.target.value}})} placeholder="Tu respuesta…"/></label>)}</div>}
}

// ── PIEZAS REUTILIZABLES: evitan repetir tarjetas y barras de progreso. ──────
function Progress({value}:{value:number}){return <div className="progress"><i style={{width:`${Math.min(100,value)}%`}}/></div>}
function Stat({label,value,note,progress}:{label:string;value:string;note:string;progress?:number}){return <article className="stat"><small>{label}</small><strong>{value}</strong><p>{note}</p>{progress!==undefined&&<Progress value={progress}/>}</article>}
function Title({title,sub,action}:{title:string;sub:string;action?:()=>void}){return <div className="title"><div><h3>{title}</h3><p>{sub}</p></div>{action&&<button onClick={action}>Abrir →</button>}</div>}
